### ISSUE TITLE
Wrong account details error not caught

### ISSUE THREAD

**Issue by almqv** [volatide/concord#1]
Very error, much crash

I ran `python concord/test2.py` and then it crashed after I inputted the wrong credentials.

**Error**
```
Traceback (most recent call last):
  File "/home/elal/Projects/clients/concord/concord/api/qrequester.py", line 42, in <lambda>
    reply.finished.connect(lambda: self._handle_request(reply))
  File "/home/elal/Projects/clients/concord/concord/api/qrequester.py", line 52, in _handle_request
    self.finished.emit(map_types(self.meta, data), info)
  File "/home/elal/Projects/clients/concord/concord/api/utils.py", line 128, in map_types
    return meta(**new)
TypeError: __init__() missing 4 required positional arguments: 'token', 'mfa', 'sms', and 'ticket'
```

This error should be handled and say something like "wrong login stuff".

**Comment by alvesvaren** [comment]
7830408 fixes this issue
